### ISSUE TITLE
User interface

### ISSUE THREAD

**Issue by badvision** [badvision/jace#21]
As a user, it would be ideal to have a non-intrusive user interface that helped me access the emulator's actions but didn't get in my way when using it.

**Comment by jpellegrini** [comment]
First -- it's a nice emulator.

I agree that a non-intrusive UI would be great. I would suggest specifically:

* possibility to configure one directory for disk images
* some hotkey to be used to remove the current disk image (and insert another one from the above mentioned directory, possibly selecting from a pull-down menu)
* easy way to insert a "newly formatted disk"

-- j

**Comment by badvision** [comment]
Thanks @jpellegrini!  This is great feedback.  I think that my reliance on hotkeys in the old UI didn't translate well in different platforms.  I switched to ctrl+shift hotkeys to be more mac-friendly and also to avoid command/windows key confusion across platforms.  Since new MacBook users don't even have function keys, and older macbook users always had trouble using FN keys too (yes, actually I had bug reports because of it), I think I need some kind of modal controls that can overlay or surround the emulation window.  Everything that can be invoked by the user as a hotkey or as an action elsewhere has been refactored to support this improvement in the future, it's just a matter of defining the concepts and creating a hotkey editor UI so users can define their own hotkeys.

**Comment by badvision** [comment]
There's now a control overlay that appears when you press the "hotdog" menu icon on the upper-right.  This enables the user to access most of the emulator's important functions.  I'll keep adding to this but closing this issue for now in favor more specific issues for individual features in the future.
