### ISSUE TITLE
6502/65c02 timing

### ISSUE THREAD

**Issue by badvision** [badvision/jace#24]
As a power developer, I want to ensure that Jace can match the exact CPU timing of either a 6502 or 65c02 CPU.  If any opcode does not use correct timing, compile tests should log the issue.  While using the emulator I would like the option to switch between the CPU timing modes.

**Comment by Archange427** [comment]
Be able to switch between 6502 and 65C02 will be a nice feature. But not only for timing but also for OPCODES!.

(and why not later, support "exotic" CPU from 6502 family)

**Comment by badvision** [comment]
Right now the way that the CPU class is structured using enumeration, it would be hard to make a class that neatly provides a 6502 abstraction and then a subsequent sub-class for 65c02, 65sc02, etc.  The issue I would run into is that I wrote it to be fast with the least amount of syntax (for java) and this would require either an expansion of the code to support cleanly, or perhaps a lot of documentation.  I like the idea though but I might make a separate issue for breaking out the 65c02 class into smaller classes since it's already quite large as it is with many nested sub-classes to support things like commands and addressing modes.

**Comment by badvision** [comment]
Not going to implement 6502 for now, but 65c02 timing is now 100% accurate and covered with unit tests to assert proper timing.
