### ISSUE TITLE
Can't mount .DSK image from command line.

### ISSUE THREAD

**Issue by Michaelangel007** [badvision/jace#28]
NOT a happy camper with the new versions.

I'm not sure if something is going on with my Java, but each new version is getting worse and worse for startup time (pressing Shift-Ctrl-C takes 3 seconds before _anything_  of the menus are displayed, expanding on "Computer" takes 5 seconds when both used to be instantaneous), Drag-n-Drop .DSK file onto the window isn't working at all, the DISK icon isn't displayed at started, and I can't even mount  DSK from the command line:

```
java -jar target/Jace.jar  -computer.s6card disk -s6.d1 ntsc.dsk 
```

Gives this error in the console:

```
Unable to find property d1 for device s6.  Try one of these :DEFAULT_VOLUME_NUMBER, USE_MAX_SPEED
```

Thankfully I have a `target/jace-2.0-SNAPSHOT-jar-with-dependencies.jar` so I'm not completely boned.

**Comment by badvision** [comment]
Hmm -- I think you're right.  I'll have to do a binary search and see at what point did this start occurring.

**Comment by badvision** [comment]
OK -- Not sure why the startup bit isn't working for commandline arguments but I got rid of that agonizing startup lurch.

**Comment by badvision** [comment]
Alright!!   This is awesome.  Now the mystery of the broken command line argument is solved as well as the horrific showstopper on startup.  We should be back to stable again.

**Comment by Michaelangel007** [comment]
Hell yeah!  Verified fix.  (My Pronto-DOS test image starts up in 2 secs now, instead of 30.) Thanks for listening to me kvitch and more importantly for getting this fixed, Blurry!!

Happy camper again as the ability to auto-mount a .DSK image from the command line will speed up my assemble+link+run dev cycle :+1: 

I really should get back to working on AppleWin; having too much fun writing 6502 assembly on the Mac. :-)

**Comment by badvision** [comment]
@Michaelangel007 Not that it's the assembler you like using, but ACME is built in if you want to make things really fast. :smiley:

**Comment by Michaelangel007** [comment]
Thanks for the mention about ACME.  I've added it to the "TO DO" list. :-)

**Comment by cewatkins** [comment]
This doesn't work again in 3.1.
