### ISSUE TITLE
[Feature Request] configurable MIDI device

### ISSUE THREAD

**Issue by joncco** [badvision/jace#31]
Is it possible to make the Passport MIDI card configurable and select something that Java already detects (such as a physical MIDI out port).  Currently it seems to be hard wired to use "Gervill" which I think is the internal Java-provided software synthesizer.

**Comment by badvision** [comment]
You're correct -- Gervil is the soft-synth.  I had already added sound out support for configuration so I can probably do something similar for the midi out.  I'll see if I can get a free hour or two to hammer away on it soon-ish. ;)

**Comment by badvision** [comment]
Consider this implemented!  Thanks for the great ideas and keep them coming. 👍  Also, when you switch devices, all-note and all-oscillator off commands are sent to every channel on the previous device so there are (hopefully!) no phantom stuck-note issues.
