### ISSUE TITLE
[FIX] MIDI device without receivers

### ISSUE THREAD

**Issue by Lutepatious** [badvision/jace#32]
Please add 3 lines in PassportMidiInterface.java for ignore MIDI device without receivers.

In Java, several MIDI devices are recognized as multiple devices with the same name only as receivers or transmitters. Ignoring devices without receivers can avoid problems.
====================================
    public void resume() {
        if (isRunning() && midiOut != null) {
            return;
        }
        try {
            MidiDevice selectedDevice = MidiSystem.getSynthesizer();
            MidiDevice.Info[] devices = MidiSystem.getMidiDeviceInfo();
            if (devices.length == 0) {
                System.out.println("No MIDI devices found");
            } else {
                for (MidiDevice.Info dev : devices) {
+                   if (MidiSystem.getMidiDevice(dev).getMaxReceivers() == 0) {
+                       continue;
+                   }
                    System.out.println("MIDI Device found: " + dev);
                    if ((preferredMidiDevice.getValue() == null && dev.getName().contains("Java Sound") && dev instanceof Synthesizer) ||
                            preferredMidiDevice.getValue().equalsIgnoreCase(dev.getName())
                        ) {
                        selectedDevice = MidiSystem.getMidiDevice(dev);
                        break;
                    }
                }
            }
            if (selectedDevice != null) {
                System.out.println("Selected MIDI device: " + selectedDevice.getDeviceInfo().getName());
                selectedDevice.open();
                midiOut = selectedDevice.getReceiver();
                super.resume();
            }
        } catch (MidiUnavailableException ex) {
            System.out.println("Could not open MIDI synthesizer");
            Logger.getLogger(PassportMidiInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

**Comment by badvision** [comment]
Cool!  Consider it done!

**Comment by badvision** [comment]
Thanks for the suggestion @Lutepatious!  Feel free to send me pull requests any time.
