### ISSUE TITLE
Fails to start on Fedora 26 with Java 1.8

### ISSUE THREAD

**Issue by gungwald** [badvision/jace#33]
This is with the latest release:

```
bill @ hpcompaq6710b ~/Dropbox/lib $ java -version
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-b16)
OpenJDK 64-Bit Server VM (build 25.141-b16, mixed mode)
bill @ hpcompaq6710b ~/Dropbox/lib $ java -jar jace.jar 
Error: Could not find or load main class jace.JaceApplication
bill @ hpcompaq6710b ~/Dropbox/lib $ 

```

**Comment by badvision** [comment]
I have overhauled this to build with Java 17 and Java 22.  It is recommended to use the Gluon version of GraalVM if you wish to build a native version.  See the updated readme for more information.  OpenJDK 22 should also work if you just want to run this as a Java application and not build a native version.
