### ISSUE TITLE
First-line of copy/paste causes syntax error on OSX with Ctrl-Shift-V

### ISSUE THREAD

**Issue by Michaelangel007** [badvision/jace#4]
With text in the system clipboard, pressing `Ctrl-Shif-V` to paste text in causes a syntax error on OSX. 

Repro.:

0. Start up Jace
1. Press `Ctrl-Delete`
2. Select this text:

    HGR
    CALL-151

3. Copy it
4. Switch to Jace
5. `Ctrl-Shift-V`
6. Emulator mangles the input so the first line causes a `?SYNTAX ERROR` :-1:

**Comment by badvision** [comment]
Ah, yeah it's a random issue where the ctrl-v is also passed in to the emulator.  I thought I had patched that but there is the possibility my fix wasn't 100%.  In the meantime you might see if it works more reliably if you hold the shift key before pressing ctrl+v just to be on the safe side.

**Comment by Michaelangel007** [comment]
Tried `Shift` + `Ctrl-V` ... no dice :-1:

**Comment by badvision** [comment]
Hmm.. try again.  I fixed the ctrl issue in the ctrl-c bugfix and I think it fixed this too.

**Comment by Michaelangel007** [comment]
Yup, verified fixed. :+1:
