### ISSUE TITLE
Ctrl-C isn't passed into Jace

### ISSUE THREAD

**Issue by Michaelangel007** [badvision/jace#9]
Repro.:

1. Start Jace
2. Press `Ctrl-Delete` to reset
3. `CALL-151`
4. Press `Ctrl-C`

Which is supposed to return you from the monitor back to Applesoft, but is ignored. :-(

**Comment by badvision** [comment]
Oh that was a very strange bug indeed!  it was passing CTRL-C but it was passing 0x31 as a keystroke every time ctrl is pressed as well.  This explains all kinds of other odd things I wasn't aware of.  Fixed.

**Comment by Michaelangel007** [comment]
:+1 verified fixed. :)
